// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbygsbeczdukacwnrznk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndieWdzYmVjemR1a2Fjd25yem5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MzM3MTgsImV4cCI6MjA2NzQwOTcxOH0.zNAX3m6sQs5jux8y9-RwM2DA6RfNrjWY2aP9Pd-cQUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});